// layouts/Footer.tsx
export default function Footer() {
  return (
    <>
      <footer className='hero-foot footer'>
        <div className='container mx-auto'>
          <p className='foot-text'>
            Copyright&nbsp;©&nbsp;2021&nbsp;
            <a href='//www.ikmoons.com'>MoonCheung</a>
            .保留所有权利&nbsp;-&nbsp;
            <a href='//beian.miit.gov.cn' target='_blank'>
              赣ICP备20001301号
            </a>
          </p>
          <p className='foot-text'>
            Powered&nbsp;By&nbsp;
            <a href='https://zh.nuxtjs.org/' target='_blank'>
              Nuxt.js
            </a>
            ，Designed&nbsp;By&nbsp;
            <a href='http://www.ikmoons.com'>MoonCheung</a>
          </p>
        </div>
      </footer>
    </>
  );
}

// components/layout/pc/Footer/index.vue
<template>
  <footer class="footer">
    <div class="container">
      <p class="foot-text">Copyright&nbsp;©&nbsp;{{getYearTime}}&nbsp;<a href="http://www.ikmoons.com"
           alt="My blog">MoonCheung</a>.保留所有权利&nbsp;-&nbsp;<a href="http://beian.miit.gov.cn"
           target="_blank"
           alt="备案号">赣ICP备20001301号</a></p>
      <p class="foot-text">Powered&nbsp;By&nbsp;<a href="https://zh.nuxtjs.org/"
           target="_blank"
           alt="Nuxt. Js's official website">Nuxt.js</a>，Designed&nbsp;By&nbsp;<a href="http://www.ikmoons.com"
           alt="My blog">MoonCheung</a></p>
    </div>
  </footer>
</template>

<script>
import { mapGetters } from 'vuex';

export default {
  name: 'VFooter',
  computed: {
    ...mapGetters({
      getYearTime: 'global/getYearTime'
    })
  }
}
</script>

<style lang="scss" scoped>
.footer {
  & > .container {
    margin: 0 auto;
    user-select: none;
    position: relative;

    & > .foot-text {
      color: $secondary-text-color;

      &:not(:last-of-type) {
        margin-bottom: $spacing-evenSize * 2;
      }
    }
  }
}
</style>
